# Generated by Django 6.0.2 on 2026-02-11 13:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.IntegerField(help_text='Padrão desejado: 0000000-00.0000.0.00.0000', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use esse padrão: 0000000-00.0000.0.00.0000', regex='^\\d{7}-\\d{2}.\\d{4}.\\d{1}.\\d{2}.\\d{4}$')])),
                ('data_criacao', models.DateTimeField()),
                ('vara', models.CharField(max_length=150)),
                ('comarca', models.CharField(max_length=200)),
                ('assunto', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('ATIVO', 'ativo'), ('ARQUIVADO', 'arquivado'), ('SUSPENSO', 'suspenso')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('CONCILIAÇÃO', 'conciliação'), ('INSTRUÇÃO', 'instrução'), ('JULGAMENTO', 'julgamento')], max_length=11)),
                ('processos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='core.processo')),
            ],
        ),
    ]
